# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'pipelines-go:$(build.buildId)'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    containerRegistry: 'Eric Jadi ACR'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Eric Jadi ACR'
    repository: 'kubecraftadmin'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'