# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'Set by Powershell script'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      displayName: Set the VersionNumber variable value
      inputs:
        targetType: 'inline'
        script: |
          [string] $dateTime = (Get-Date -Format 'yyyyMMdd.HHmmss')
          Write-Host "##vso[task.setvariable variable=tag]$dateTime"
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'erjadi/kubecraftadmin'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
