# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build and Push
  displayName: Build and Push image
  jobs:  
  - job: Build and Push
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'erjadi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          erjadi/KubeCraftAdmin:$(tag)
          erjadi/KubeCraftAdmin:latest