# permissions for end users to view kubecrafts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecraft-viewer-role
rules:
- apiGroups:
  - cache.kubecraft.com
  resources:
  - kubecrafts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.kubecraft.com
  resources:
  - kubecrafts/status
  verbs:
  - get
