apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kubecraft-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Kubernetes administration through Minecraft
  displayName: Kubecraft Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubernetes
  - minecraft
  - fun
  links:
  - name: Kubecraft Operator
    url: https://kubecraft-operator.domain
  maturity: alpha
  provider:
    name: Keith Tenzer
    url: https://github.com/ktenzer/kubecraftadmin
  version: 0.0.0
